EditHome
albertnahas/biobibar pull request #3
Opened 2023-01-16 14:38 UTC by pomogaeva

2023-01-17 09:53 UTC, albertnahas commented on components/CustomerCard.tsx
> +            className="input input-readonly"
in className no need to say "input input-readonly"
Make "input-readonly" components apply "input" from css, example:
`  .input-readonly {
    @apply input cursor-default ...
  }`

2023-01-17 09:53 UTC, albertnahas commented on components/EditCoverSection.tsx
> +    switch (name) {
Why do we need switch statement here?
All three cases look identical

2023-01-17 09:53 UTC, albertnahas commented on components/EditCoverSection.tsx
> +    console.log(home.slogan);
remove `console.log`

2023-01-17 09:53 UTC, albertnahas commented on components/EditCoverSection.tsx
> +        setHome({ ...home, [inputName]: imageUrl });
Show a toaster that the image was uploaded successfully
`toast.sucess("...")`

2023-01-17 09:53 UTC, albertnahas commented on components/EditCoverSection.tsx
> +      console.error("Image size is too large");
Show a toaster with an error message
`toast.error("...")`

2023-01-17 09:53 UTC, albertnahas commented on components/EditCoverSection.tsx
> +              {isOpen === "cover" && (
Having a different popup element for each image is very redundant,
We need to use one popup and only change it's location on the screen based on the element

2023-01-17 09:53 UTC, albertnahas commented on components/EditCoverSection.tsx
> +                  <label htmlFor="image">
No need for label for view

2023-01-17 09:53 UTC, albertnahas commented on components/EditCoverSection.tsx
> +                className="input input-primary col-span-3"
in className no need to say "input input-primary"
Make "input-primary" components apply "input" from css, example:
  .input-primary{ @apply input ... }

2023-01-17 11:22 UTC, albertnahas requested changes

2023-01-17 11:22 UTC, albertnahas commented on atoms/EditMenuPopup.tsx
> +const EditMenuPopup = ({
Rename to `EditImageMenu`

2023-01-17 11:22 UTC, albertnahas commented on atoms/EditMenuPopup.tsx
> +    <div className="cover-edit-container">
change class `cover` to be more generic

2023-01-17 11:22 UTC, albertnahas commented on atoms/EditMenuPopup.tsx
> +  handleView: (e: any) => void,
Try not to use `any`

2023-01-17 11:22 UTC, albertnahas commented on components/EditCoverSection.tsx
>          setHome({ ...home, [inputName]: imageUrl });
Add success toast

2023-01-17 11:22 UTC, albertnahas commented on atoms/EditMenuPopup.tsx
> +  handleUploadImageClick: () => void,
We don't need to pass this function as a prop, it doesn't have any external usage.
instead just move it inside the component

2023-01-17 12:40 UTC, pomogaeva commented on components/EditCoverSection.tsx
>          setHome({ ...home, [inputName]: imageUrl });
It's already there

2023-01-17 20:32 UTC, albertnahas requested changes

2023-01-17 20:32 UTC, albertnahas commented on components/EditCoverSection.tsx
> +    lightbox.style.position = "fixed";
Instead of adding multiple lines for style we can create a class or component in our global.css

2023-01-17 20:32 UTC, albertnahas commented on components/EditCoverSection.tsx
> +    image.style.position = "absolute";
Instead of adding multiple lines for style we can create a class or component in our global.css

2023-01-17 20:32 UTC, albertnahas commented on components/EditCoverSection.tsx
> +    closeButton.style.position = "absolute";
Instead of adding multiple lines for style we can create a class or component in our global.css

2023-01-18 13:17 UTC, albertnahas requested changes

2023-01-18 13:17 UTC, albertnahas commented on styles/globals.css
>      @apply fixed top-0 bottom-0 left-0 right-0 bg-text bg-opacity-80;
Cool thing about tailwind, you can replace `top-0 bottom-0 left-0 right-0` with `inset-0`

2023-01-19 10:47 UTC, albertnahas requested changes

2023-01-19 10:47 UTC, albertnahas commented on components/EditCoverSection.tsx
> +        document.body.style.overflow = "scroll";
overflow should be `auto`

2023-01-19 15:50 UTC, albertnahas approved these changes

2023-01-19 15:51 UTC, merged